disabled_rules:
  - trailing_whitespace
  - force_try

opt_in_rules:
  - conditional_returns_on_newline
  - empty_count
  - missing_docs
  - operator_usage_whitespace

# 対象のファイル・フォルダ
# デフォルトからフォルダ名を変更していない場合、プロジェクト名と同名のフォルダを指定すればいい
included:
  - {syncronizedTimer}

# 対象外のファイル・フォルダ
# CocoaPodsでインストールしたライブラリは対象外とする
excluded:
  - Pods


